//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDeviceManagerAgent.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsDeviceManagerAgent.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アンチウィルスソフトウェア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AntiVirusSoftware {
            get {
                return ResourceManager.GetString("AntiVirusSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIOSの製造元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BIOSManufacturer {
            get {
                return ResourceManager.GetString("BIOSManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIOSのバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BIOSVersion {
            get {
                return ResourceManager.GetString("BIOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BitLockerの状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatus {
            get {
                return ResourceManager.GetString("BitLockerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての固定ディスクが無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAllDiskDisable {
            get {
                return ResourceManager.GetString("BitLockerStatusAllDiskDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての固定ディスクが有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAllDiskEnable {
            get {
                return ResourceManager.GetString("BitLockerStatusAllDiskEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが復号化中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskDecrypting {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskDecrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskDisable {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが暗号化中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskEncrypting {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskEncrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが有効(ロック) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskOnLocked {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskOnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが中断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskSuspended {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクが状態不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskUnknown {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いずれかの固定ディスクがアクティブ化を待機中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatusAnyDiskWaitingForActivation {
            get {
                return ResourceManager.GetString("BitLockerStatusAnyDiskWaitingForActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   =====収集結果ここまで===== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectResultEnd {
            get {
                return ResourceManager.GetString("CollectResultEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   =====収集結果ここから===== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectResultStart {
            get {
                return ResourceManager.GetString("CollectResultStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンピュータの製造元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComputerManufacturer {
            get {
                return ResourceManager.GetString("ComputerManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンピュータの製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComputerModel {
            get {
                return ResourceManager.GetString("ComputerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理の結果をファイルに出力します｡(--output [json|xml|csv]) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextOutput {
            get {
                return ResourceManager.GetString("HelpTextOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理の結果を詳細に表示します｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextVerbose {
            get {
                return ResourceManager.GetString("HelpTextVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===重要なお知らせ=== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Javaのバージョンチェック結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JavaVersioncheckResult {
            get {
                return ResourceManager.GetString("JavaVersioncheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageComplete {
            get {
                return ResourceManager.GetString("MessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルを生成しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreateCsvFile {
            get {
                return ResourceManager.GetString("MessageCreateCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースファイルを生成しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreateDatabase {
            get {
                return ResourceManager.GetString("MessageCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSONファイルを生成しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreateJsonFile {
            get {
                return ResourceManager.GetString("MessageCreateJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XMLファイルを生成しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreateXmlFile {
            get {
                return ResourceManager.GetString("MessageCreateXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースファイルが見つかりません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDatabaseNotFound {
            get {
                return ResourceManager.GetString("MessageDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   古いバージョンのデータベースファイルを検出しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDetectOldDatabase {
            get {
                return ResourceManager.GetString("MessageDetectOldDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を[FatalErrorInformation.log]に保存しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowsデバイス情報を収集中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNowCollecting {
            get {
                return ResourceManager.GetString("MessageNowCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何かのキーを押下してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePause {
            get {
                return ResourceManager.GetString("MessagePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご協力ありがとうございました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageThanks {
            get {
                return ResourceManager.GetString("MessageThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースファイルをバージョンアップしました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUpdateDatabaseComplete {
            get {
                return ResourceManager.GetString("MessageUpdateDatabaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSビルド番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSBuildNumber {
            get {
                return ResourceManager.GetString("OSBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OS名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSName {
            get {
                return ResourceManager.GetString("OSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセッサ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未検出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undetected {
            get {
                return ResourceManager.GetString("Undetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
