//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDeviceManagerAgent.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsDeviceManagerAgent.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   処理の結果を詳細に表示します｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextVerbose {
            get {
                return ResourceManager.GetString("HelpTextVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===重要なお知らせ=== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageComplete {
            get {
                return ResourceManager.GetString("MessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を[FatalErrorInformation.log]に保存しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowsデバイス情報を収集中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNowCollecting {
            get {
                return ResourceManager.GetString("MessageNowCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何かのキーを押下してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePause {
            get {
                return ResourceManager.GetString("MessagePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご協力ありがとうございました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageThanks {
            get {
                return ResourceManager.GetString("MessageThanks", resourceCulture);
            }
        }
    }
}
