//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDeviceManagerViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsDeviceManagerViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アンチウィルスソフトウェア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AntiVirusSoftware {
            get {
                return ResourceManager.GetString("AntiVirusSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowsDeviceManagerViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIOSの製造元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BIOSManufacturer {
            get {
                return ResourceManager.GetString("BIOSManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIOSのバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BIOSVersion {
            get {
                return ResourceManager.GetString("BIOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BitLockerの状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitLockerStatus {
            get {
                return ResourceManager.GetString("BitLockerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要領域の整理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンピュータの製造元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComputerManufacturer {
            get {
                return ResourceManager.GetString("ComputerManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンピュータの製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComputerModel {
            get {
                return ResourceManager.GetString("ComputerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CSVFile {
            get {
                return ResourceManager.GetString("CSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示項目設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayItemSetting {
            get {
                return ResourceManager.GetString("DisplayItemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Javaのバージョンチェック結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JavaVersioncheckResult {
            get {
                return ResourceManager.GetString("JavaVersioncheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSONファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSONFile {
            get {
                return ResourceManager.GetString("JSONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースメンテナンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要領域の整理が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCleanComplete {
            get {
                return ResourceManager.GetString("MessageCleanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースファイルが見つかりません｡
        ///このアプリケーションを終了します｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageErrorDatabaseNotFound {
            get {
                return ResourceManager.GetString("MessageErrorDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するCSVファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageErrorOutputCsvFileNotSelected {
            get {
                return ResourceManager.GetString("MessageErrorOutputCsvFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するJSONファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageErrorOutputJsonFileNotSelected {
            get {
                return ResourceManager.GetString("MessageErrorOutputJsonFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するXMLファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageErrorOutputXmlFileNotSelected {
            get {
                return ResourceManager.GetString("MessageErrorOutputXmlFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションのプロジェクトURLを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOpenProjectUrl {
            get {
                return ResourceManager.GetString("MessageOpenProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV出力が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOutputCsvComplete {
            get {
                return ResourceManager.GetString("MessageOutputCsvComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON出力が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOutputJsonComplete {
            get {
                return ResourceManager.GetString("MessageOutputJsonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML出力が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOutputXmlComplete {
            get {
                return ResourceManager.GetString("MessageOutputXmlComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSバージョン再判定が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageRecheckOSVersionComplete {
            get {
                return ResourceManager.GetString("MessageRecheckOSVersionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込みが完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageReloadComplete {
            get {
                return ResourceManager.GetString("MessageReloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースファイルを選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectDatabaseFile {
            get {
                return ResourceManager.GetString("MessageSelectDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するCSVファイルを選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectOutputCsvFile {
            get {
                return ResourceManager.GetString("MessageSelectOutputCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するJSONファイルを選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectOutputJsonFile {
            get {
                return ResourceManager.GetString("MessageSelectOutputJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するXMLファイルを選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectOutputXmlFile {
            get {
                return ResourceManager.GetString("MessageSelectOutputXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未収集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotCollected {
            get {
                return ResourceManager.GetString("NotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSビルド番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSBuildNumber {
            get {
                return ResourceManager.GetString("OSBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OS名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSName {
            get {
                return ResourceManager.GetString("OSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputCsv {
            get {
                return ResourceManager.GetString("OutputCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputJson {
            get {
                return ResourceManager.GetString("OutputJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputXml {
            get {
                return ResourceManager.GetString("OutputXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセッサ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSバージョン再判定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecheckOSVersion {
            get {
                return ResourceManager.GetString("RecheckOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLiteデータベースファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SQLiteDatabaseFile {
            get {
                return ResourceManager.GetString("SQLiteDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowsデバイス情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowsDeviceInfo {
            get {
                return ResourceManager.GetString("WindowsDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XMLファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XMLFile {
            get {
                return ResourceManager.GetString("XMLFile", resourceCulture);
            }
        }
    }
}
